version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "7156:7156"
    volumes:
      - ./Server:/app
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:8080"
      - "443:7156"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - client
      - server
